# Linux-specific zsh configuration
# Make a directory, then change into it
mkcd() {
    [[ ! -d "${1}" ]] && gmkdir --parents -- "${1}"
    cd "${1}" || exit
}

autoload -Uz mkcd

rgenv () {
    if [[ -n $1 ]]; then
        env | rg --ignore-case $1
    else
        return 0
    fi
}
